<a href="https://colab.research.google.com/github/hoangtrungnguyen18072k5-gif/TH_DeepLearning/blob/main/Tuan1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

import numpy as np

print("--- CÂU 1 & 2 ---")
# 1 & 2. Tạo ma trận 3x3 ngẫu nhiên [0, 20].
arr_1_2 = np.random.randint(0, 21, size=(3, 3))
print("Ma trận:\n", arr_1_2)
# Kiểm tra tất cả khác 0 (hàm all) [cite: 573]
print("Tất cả phần tử khác 0:", np.all(arr_1_2 != 0))
# Kiểm tra tồn tại phần tử khác 0 (hàm any) [cite: 574]
print("Tồn tại phần tử khác 0:", np.any(arr_1_2 != 0))

print("\n--- CÂU 3 ---")
# 3. Dùng numpy.greater, greater_equal, less, less_equal so sánh 2 mảng. [cite: 574]
a1 = np.array([1, 5, 9])
a2 = np.array([5, 5, 5])
print("a1 > a2:", np.greater(a1, a2))
print("a1 >= a2:", np.greater_equal(a1, a2))
print("a1 < a2:", np.less(a1, a2))
print("a1 <= a2:", np.less_equal(a1, a2))

print("\n--- CÂU 4 ---")
# 4. Mảng gồm mười số 1, mười số 0 và mười số 5. [cite: 575]
arr_4 = np.concatenate([np.ones(10), np.zeros(10), np.full(10, 5)])
print(arr_4)

print("\n--- CÂU 5 ---")
# 5. Mảng số nguyên chẵn từ 30 đến 70. [cite: 576]
arr_5 = np.arange(30, 71, 2)
print(arr_5)

print("\n--- CÂU 6 ---")
# 6. Ma trận đơn vị 3x3. [cite: 577]
arr_6 = np.identity(3)
print(arr_6)

print("\n--- CÂU 7 ---")
# 7. Mảng 10 phần tử [15, 55], in các giá trị trừ phần tử đầu và cuối. [cite: 581, 582]
arr_7 = np.linspace(15, 55, 10)
print(arr_7[1:-1])

print("\n--- CÂU 8 ---")
# 8. Mảng 20 phần tử [0, 20], đổi dấu số nằm trong khoảng [9, 15]. [cite: 583]
arr_8 = np.arange(21)
arr_8[(arr_8 >= 9) & (arr_8 <= 15)] *= -1
print(arr_8)

print("\n--- CÂU 9 ---")
# 9. Ma trận 3x4 có giá trị [10, 21]. [cite: 584]
arr_9 = np.random.randint(10, 22, size=(3, 4))
print(arr_9)

print("\n--- CÂU 10 ---")
# 10. Ma trận 10x10, biên bằng 1, bên trong bằng 0. [cite: 585]
arr_10 = np.ones((10, 10))
arr_10[1:-1, 1:-1] = 0
print(arr_10)

print("\n--- CÂU 11 ---")
# 11. Ma trận 5x5 đường chéo chính là 1, 2, 3, 4, 5. [cite: 586]
arr_11 = np.diag([1, 2, 3, 4, 5])
print(arr_11)

print("\n--- CÂU 12 ---")
# 12. Mảng 3x3x3 tính tổng theo mỗi dòng, mỗi cột. [cite: 587]
arr_12 = np.random.randint(1, 10, size=(3, 3, 3))
print("Tổng theo cột (axis=0):\n", np.sum(arr_12, axis=0))
print("Tổng theo dòng (axis=1):\n", np.sum(arr_12, axis=1))

print("\n--- CÂU 13 ---")
# 13. 2 vector ngẫu nhiên 10 phần tử, tính inner product. [cite: 588]
v1 = np.random.rand(10)
v2 = np.random.rand(10)
print("Inner product:", np.dot(v1, v2))

print("\n--- CÂU 14 ---")
# 14. Ma trận A(4x3), vector y(3). Thêm y vào từng dòng của A. [cite: 589, 590]
A = np.random.randint(1, 10, size=(4, 3))
y = np.random.randint(1, 10, size=(3,))
print("A + y:\n", A + y)





--- CÂU 1 & 2 ---
Ma trận:
 [[16  2  2]
 [18 17 16]
 [10 20 11]]
Tất cả phần tử khác 0: True
Tồn tại phần tử khác 0: True

--- CÂU 3 ---
a1 > a2: [False False  True]
a1 >= a2: [False  True  True]
a1 < a2: [ True False False]
a1 <= a2: [ True  True False]

--- CÂU 4 ---
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]

--- CÂU 5 ---
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

--- CÂU 6 ---
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

--- CÂU 7 ---
[19.44444444 23.88888889 28.33333333 32.77777778 37.22222222 41.66666667
 46.11111111 50.55555556]

--- CÂU 8 ---
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]

--- CÂU 9 ---
[[14 21 12 20]
 [17 18 10 13]
 [20 19 14 13]]

--- CÂU 10 ---
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 

# Mục mới

In [5]:
import pandas as pd
import numpy as np

print("--- CÂU 15 ---")
# 15. Cộng, trừ, nhân, chia 2 Series [cite: 591]
s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])
print("Cộng:\n", s1 + s2)
print("Trừ:\n", s1 - s2)
print("Nhân:\n", s1 * s2)
print("Chia:\n", s1 / s2)

print("\n--- CÂU 16 ---")
# 16. Chuyển đổi cột đầu tiên của DataFrame thành Series [cite: 592]
df_16 = pd.DataFrame({'col1': [1, 2, 3, 4, 5, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1, 11]})
s_col1 = df_16.iloc[:, 0] # Dùng iloc lấy mọi dòng của cột index 0
print(s_col1)

print("\n--- CÂU 17 ---")
# 17. Sắp xếp DataFrame 4x3 ngẫu nhiên theo cột [cite: 634]
df_17 = pd.DataFrame(np.random.rand(4, 3), columns=['A', 'B', 'C'])
print("Sort theo cột A:\n", df_17.sort_values(by='A'))

print("\n--- CÂU 18 ---")
# 18. Thay đổi index của Series [cite: 635]
s_18 = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
s_reindexed = s_18.reindex(['B', 'A', 'C', 'D', 'E'])
print(s_reindexed)

print("\n--- CÂU 19 ---")
# 19. Tìm phần tử trong Series x không có trong Series y (hàm isin) [cite: 662, 663]
sx = pd.Series([1, 2, 3, 4, 5])
sy = pd.Series([2, 4, 6, 8, 10])
print(sx[~sx.isin(sy)])

print("\n--- CÂU 20 ---")
# 20. numpy.union1d, intersect1d trên 2 Series ngẫu nhiên 20 phần tử [cite: 680]
sx_20 = pd.Series(np.random.randint(0, 50, 20))
sy_20 = pd.Series(np.random.randint(0, 50, 20))
print("Hội (Union):\n", np.union1d(sx_20, sy_20))
print("Giao (Intersection):\n", np.intersect1d(sx_20, sy_20))

print("\n--- CÂU 21 ---")
# 21. Thêm series y vào x theo chiều dọc, ngang [cite: 681]
sx_21 = pd.Series([0, 1, 2, 7, 8, 9])
sy_21 = pd.Series(['p', 'q', 'r', 'v', 'w', 'x', 'y'])
print("Theo chiều dọc:\n", pd.concat([sx_21, sy_21], axis=0, ignore_index=True))
print("\nTheo chiều ngang:\n", pd.concat([sx_21, sy_21], axis=1))

print("\n--- CÂU 22 ---")
# 22. Tạo DataFrame từ exam_data [cite: 706, 707, 708, 709, 710]
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df_22 = pd.DataFrame(exam_data, index=labels)
print(df_22)

print("\n--- CÂU 23 ---")
# 23. 3 dòng đầu tiên [cite: 712]
print(df_22.head(3))

print("\n--- CÂU 24 ---")
# 24. Chọn cột 'name' và 'score' [cite: 713]
print(df_22[['name', 'score']])

print("\n--- CÂU 25 ---")
# 25. Những dòng có attempts > 2 [cite: 714]
print(df_22[df_22['attempts'] > 2])

print("\n--- CÂU 26 ---")
# 26. Số dòng, số cột của DataFrame [cite: 715]
rows, cols = df_22.shape
print(f"Số dòng: {rows}, Số cột: {cols}")

print("\n--- CÂU 27 ---")
# 27. Dòng có score là NaN [cite: 716]
print(df_22[df_22['score'].isnull()])

print("\n--- CÂU 28 ---")
# 28. Dòng có score trong khoảng (15, 20) [cite: 717]
print(df_22[df_22['score'].between(15, 20, inclusive='neither')])

print("\n--- CÂU 29 ---")
# 29. Dòng có attempts > 2 và score trong khoảng (15, 20) [cite: 718]
print(df_22[(df_22['attempts'] > 2) & (df_22['score'].between(15, 20, inclusive='neither'))])

print("\n--- CÂU 30 ---")
# 30. Thay đổi giá trị dòng 'd', cột score là 19 [cite: 719]
df_22.loc['d', 'score'] = 19
print(df_22.loc['d'])

--- CÂU 15 ---
Cộng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64

--- CÂU 16 ---
0     1
1     2
2     3
3     4
4     5
5    11
Name: col1, dtype: int64

--- CÂU 17 ---
Sort theo cột A:
           A         B         C
1  0.574253  0.391189  0.003958
2  0.612684  0.258167  0.055803
3  0.668259  0.283353  0.638225
0  0.963673  0.627170  0.818955

--- CÂU 18 ---
B    2
A    1
C    3
D    4
E    5
dtype: int64

--- CÂU 19 ---
0    1
2    3
4    5
dtype: int64

--- CÂU 20 ---
Hội (Union):
 [ 0  2  3  6  7  8  9 10 12 13 16 19 21 23 24 25 26 27 28 29 30 31 33 36
 37 40 42 43 46 48]
Giao (Intersection):
 [ 6 12 21 31]

--- CÂU 21 ---
Theo chiều dọc:
 0     0
1     1
2     2
3     7
4     8
5     9
6     p
7     q
8     r
9     v
10    w
11    x
12    y
dtype: object

Theo c

# Mục mới